system:
    ezdemo_site_clean_group:
        location_view:
            full:
                my_ruleset:
                    controller: NetgenSearchAndFilterBundle:Search:searchLocation
                    match:
                        Identifier\ContentType: [search_folder, rgm_review_labels]
        user:
            login_template: "NetgenSimpleContentStorageBundle:user:login.html.twig"
