system:
    default:
        field_templates:
            - {template: "NetgenBirthdayBundle::ezbirthday_content_field.html.twig", priority: 0}
        fielddefinition_settings_templates:
            - {template: "NetgenBirthdayBundle:platformui/content_type/view:ezbirthday.html.twig", priority: 0}
