parameters:
    ezpublish.fieldType.ezbirthday.class: Netgen\BirthdayBundle\Core\FieldType\Birthday\Type
    ezpublish.fieldType.childrenindexer.class: %ezpublish.fieldType.eznull.class%

services:
    ezpublish.fieldType.ezbirthday:
        class: %ezpublish.fieldType.ezbirthday.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezbirthday}
    ezpublish.fieldType.childrenindexer:
        class: %ezpublish.fieldType.childrenindexer.class%
        parent: ezpublish.fieldType
        arguments: [ "childrenindexer" ]
        tags:
            - {name: ezpublish.fieldType, alias: childrenindexer}