services:
    netgen_birthday.field_type:
        class: Netgen\Bundle\BirthdayBundle\Core\FieldType\Birthday\Type
        public: true
        parent: ezpublish.fieldType
        tags:
            - { name: ezpublish.fieldType, alias: ezbirthday }

    netgen_birthday.field_type.legacy.converter:
        class: Netgen\Bundle\BirthdayBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Birthday
        public: false
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: ezbirthday, lazy: true, callback: '::create' }

    netgen_birthday.field_type.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        public: false
        tags:
            - { name: ezpublish.fieldType.indexable, alias: ezbirthday }
