imports:
    - {resource: form_fieldtype_handlers.yml}

services:
#    netgen_birthday.example:
#        class: Netgen\BirthdayBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
