parameters:
    ezpublish.fieldType.ezbirthday.class: Netgen\Bundle\BirthdayBundle\Core\FieldType\Birthday\Type
    ezpublish.fieldType.ezbirthday.converter.class: Netgen\Bundle\BirthdayBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Birthday

services:
    ezpublish.fieldType.ezbirthday:
        class: %ezpublish.fieldType.ezbirthday.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezbirthday}

    ezpublish.fieldType.ezbirthday.converter:
        class: %ezpublish.fieldType.ezbirthday.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezbirthday, lazy: true, callback: '::create'}
